name: faastermetrics
channels:
  - defaults
dependencies:
  - appnope=0.1.0
  - astroid=2.3.3
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - decorator=4.4.2
  - entrypoints=0.3
  - flake8=3.7.9
  - freetype=2.9.1
  - intel-openmp=2019.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.17.0
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pylint=2.4.4
  - pyparsing=2.4.7
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - argmagic
    - json_coder

